food_recipes/food_recipes/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.views import serve

handler404 = 'main.views.not_found_view'


urlpatterns = [
    path("admin/", admin.site.urls),
    # path("recipes/", include('recipes.urls')),
    path("users/", include('users.urls')),
    path("", include('main.urls')),
    
    # path("home/", include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
urlpatterns += static(settings.STATIC_URL, view=serve)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns=[
        path('__debug/__', include(debug_toolbar.urls)),
    ]+ urlpatterns
    
    urlpatterns+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель администрирования сайта"
admin.site.site_title = "Admin game"

food_recipes/main/urls.py
from django.contrib import admin
from django.urls import path, re_path

from . import views

app_name = "main"


urlpatterns = [
    path("", views.index, name="main"),
    # path('product/<int:a>/details/<int:b>',views.get_demo),
    # path('calc/<int:a>/<slug:operation>/<int:b>',views.calc),
    # path("profile/", views.profile, name="profile"),
    path("foodlist/<int:cat_id>/", views.foodlist, name="foodlist"),
    path("gallery/", views.gallery, name="gallery"),
    path("about/<int:id>/", views.details, name="details"),
    path("stared/<int:id>/", views.stared, name="star"),
    path("contacts/", views.contacts, name="contacts"),
    path("userstop/", views.users_top, name="top"),
    path("add/", views.add_recipe, name="add_rec"), #as_view()
    path("update/<int:pk>/", views.RecipeUpdateView.as_view(), name="rec_update"),
    path("delete/<int:pk>/", views.RecipeDeleteView.as_view(), name="rec_delete"),
    # path("login/", views.loginView, name="login"),
    
]

food_recipes/users/urls.py
from django.contrib import admin
from django.urls import path, re_path

from . import views

app_name = "users"

urlpatterns = [
    path("<int:pk>/", views.AccountDetailView.as_view(), name="user"),
    path("user/<int:pk>/", views.UserAccountView.as_view(), name="account"),
    # path("about/<int:id>/", views.details, name="details"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.loginView, name="login"),
    
]

food_recipes/main/forms.py
from django import forms

from django.contrib.auth.models import User

from .models import File, Recipe


class ProfileForm(forms.Form):
    name = forms.CharField(label="Имя", max_length=40, strip=True)
    gender = forms.CharField(label="Пол", max_length=10, required=False)
    age = forms.DecimalField(label="Возраст", min_value=1, max_value=200, 
                             max_digits=3, required=False)
    info = forms.CharField(label="Информация", 
                           widget=forms.Textarea(attrs={'cols': 40, 'rows': 7}), required=False, 
                           strip=True)




# from django.forms import ModelForm, Textarea, CheckboxSelectMultiple, Select
# from .models import *

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result

# class FileFieldForm(forms.ModelForm):
#     file = MultipleFileField()
#     class Meta:
#         model = File

#         fields = ['file']

class RecipeAddForm(forms.ModelForm):
    file = MultipleFileField(required=False)

    class Meta:
        model = Recipe
        fields = ['title','description','category']


from django.forms import inlineformset_factory
ImagesFormSet = inlineformset_factory(Recipe, File, fields=("file",),extra=1,max_num=4,
    widgets={
        "image_field": MultipleFileField(required=False),
    })
# class RecipeForm(forms.ModelForm):
#     # account_image = forms.
#     nickname = forms.CharField(label="Имя", max_length=40, strip=True)
#     gender = forms.CharField(label="Пол", max_length=10, required=False)
#     birthdate = forms.DateField(label='Дата рождения', required=False)
#     age = forms.DecimalField(label="Возраст", min_value=1, max_value=200, 
#                              max_digits=3, required=False)
#     info = forms.CharField(label="Информация", 
#                            widget=forms.Textarea(attrs={'cols': 40, 'rows': 7}), required=False, 
#                            strip=True)
#     account_image = forms.ImageField(label='Аватар', required=False)

#     class Meta:
#         model = Recipe
#         fields = ['title','description','category']

food_recipes/main/views.py
import datetime
from typing import Any
from django.db import models
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.messages import get_messages
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Avg, Max
from django.views.generic import DetailView, DeleteView, UpdateView, CreateView
from django.views import View
from django.contrib import messages
from django.conf import settings
from django.db.models.query_utils import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

from .models import Recipe, File, Category
from .forms import *
from users.models import Account, VotesConnection


def index(request):
    context = {
        "title": "Главная страница",
        "recipes": tuple(),
        "files": tuple(),
        "search_res": False,
        'total': 0,
        "liked": find_what_liked(request)
    }
    page_number = request.GET.get('page')

    if request.method == "POST":
        page_number = 0
        title = request.POST.get("title", False)
        my_rec = request.POST.get("my_recipes", False)
        if title:
            title = title.strip()
            recipes_page, files, total = get_recipes_and_first_file(with_filter={'title': title}, page_number=page_number)
        
        elif my_rec:
            if request.user.id:
                recipes_page, files, total = get_recipes_and_first_file(with_filter={'author': request.user.id}, page_number=page_number)

        else:
            recipes_page, files, total = get_recipes_and_first_file()
        
        context["recipes"] = recipes_page
        context['files'] = files
        context["search_res"] = title
        context["title"] = "Главная страница" if not my_rec  else "Мои рецепты"
        context['total'] = total
      
        return render(request, "main/index.html", context)
    winners = Recipe.objects.annotate(Count('votes', distinct=True))

    recipes_page, files, total = get_recipes_and_first_file(False, page_number)

    context["recipes"] = recipes_page
    context['files'] = files
    context['total'] = total
    return render(request, "main/index.html", context)


def sidebar(request):
    return render(
        request, "main/sidebar.html"
    )


def users_top(request):
    '''топ юзеров по количеству рецептов'''
    users_top = User.objects.annotate(Count('recipe', distinct=True)).select_related('account').order_by('-recipe__count')
    # .values('account__nickname, recipe__count')
    # cnt.first().recipe__count
    context = {'users_top': users_top}
    return render(request, "main/users_top.html", context)


def contacts(request):
    context = {
        "title": "Контакты",
    }
    return render(request, "main/contacts.html", context)



def foodlist(request, cat_id):
    """по категориям"""
    recipes = Recipe.objects.filter(category__id=cat_id).all()
    category = Category.objects.filter(id=cat_id).first()

    total = len(recipes)
    page_number = request.GET.get('page')

    page_paginator = Paginator(recipes, per_page=4)
    recipes_page = page_paginator.get_page(page_number)

    # print([(rec.id, rec.description) for rec in recipes])
    recs_id_list = [rec.id for rec in recipes_page]
    print(recs_id_list)
    recs = File.objects.filter(recipe__in=recs_id_list).values("recipe", "file")
    files = {int(file["recipe"]): (file["file"],) for file in recs}
    # print('files',files)
    liked_recipes_dict = find_what_liked(request)

    context = {
        "title": "Категория",
        'food_type': category.food_type if category else None,
        "recipes": recipes_page,
        "files": files,
        "liked": liked_recipes_dict,
        'total': total
    }
    return render(request, "main/foodlist.html", context)


def gallery(request):
    page_number = request.GET.get('page')

    recipes_page, files, total = get_recipes_and_first_file(False, page_number)
    liked_recipes_dict = find_what_liked(request)

    context = {
        "title": "Галерея",
        "recipes": recipes_page,
        "files": files,
        "liked": liked_recipes_dict,
        'total': total
    }
    return render(request, "main/gallery.html", context)


def find_what_liked(request):
    if not request.user or not request.user.id:
        ...# user='anonymous'
        return {}
    else:
        user = Account.objects.get(user=request.user.id)
        
        liked_recipes_dict = {}
        # VotesConnection(recipe=rec1, user=user
        for rec in user.likes_recipes.all():
            liked_recipes_dict[rec.id] = 1
        return liked_recipes_dict


def stared(request, id):
    try:
        id = int(id)
    except Exception:
        return not_found_view(request=request, exception='')
    rec1 = Recipe.objects.filter(id=id).first()
    if not rec1:
        print('-----not found recipe-', id)
        return not_found_view(request=request, exception='')
    if not request.user or not request.user.id:
        ...# user='anonymous'
        return HttpResponse('fail')
    else:
        user = Account.objects.get(user=request.user.id)
        liked = VotesConnection.objects.filter(
                recipe=rec1, user=user).first()
        if not liked:
            VotesConnection(recipe=rec1, user=user).save()

            rec1.votes += 1
            rec1.save()
        else:
            return HttpResponse('voted')
    return HttpResponse('success')


def details(request, id):
    rec1 = Recipe.objects.filter(id=id).select_related('author').first()
    if not rec1:
        return not_found_view(request=request, exception='')
    account = Account.objects.get(user=rec1.author)
    # .values_list('title', 'author', 'date', 'id', 'description')
    files = File.objects.filter(recipe=id)
    print("details files", files)
    liked_recipes_dict = find_what_liked(request)

    context = {
        "title": "",
        "recipe": rec1,
        "files": files,
        'account': account,
        "liked": liked_recipes_dict
    }
    return render(request, "main/recipe.html", context)


def not_found_view(request, exception):
    return render(request, "main/404.html")


def get_files_of_recipe(rec_id):
    rec1 = Recipe.objects.filter(id=rec_id).first()
    return File.objects.filter(recipe=rec1)


def save_new_file(request):
    recipe_id = request.POST.get("recipe_id")
    filename = request.POST.get("filename")

    if not filename and not recipe_id:
        ...
    else:
        recipe_obj = Recipe.objects.get(id=recipe_id)
        new_file = File(filename=filename, rec_id=recipe_obj)
        new_file.save()



def get_recipes_and_files():
    recipes = Recipe.objects.select_related("author").prefetch_related("images").all()
    print([(r.id, r.images.all()) for r in recipes])
    files =  {int(file.id): [ff.file for ff in file.images.all()]  for file in recipes}
    # print('gallery files', [list([ff.file for ff in v]) for f,  v in files.items()])
    print('gallery files', files)
    return recipes, files


def get_recipes_and_first_file(with_filter=False, page_number=0):
    if not with_filter:
        recipes = Recipe.objects.select_related("author").prefetch_related("images").order_by('-date').all()
    elif with_filter.get('author'):
        recipes = Recipe.objects.filter(author=with_filter.get('author')).select_related("author").prefetch_related("images").order_by('-date').all()
    else:
        title = with_filter.get('title')
        recipes = Recipe.objects.select_related("author").prefetch_related("images").filter(Q(title__icontains=title)|Q(description__icontains=title)).order_by('-date')
    
    # print([(r.id, r.images.first()) for r in recipes])
    total = len(recipes)
    page_paginator = Paginator(recipes,per_page=8)
    recipes_page_obj = page_paginator.get_page(page_number)

    files =  {int(file.id): [file.images.first().file if file.images.first() else None]  for file in recipes_page_obj}
    # print('gallery files', files)    

    return recipes_page_obj, files, total



@login_required(login_url=settings.LOGIN_URL)
def add_recipe(request):
    if request.method == 'POST':
        if not request.user.id:
            return HttpResponse('вы не залогинены')
        form = RecipeAddForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            new_recipe = form.save(commit=False)
            new_recipe.author = current_user
            new_recipe.save()
            form.save_m2m()
            all_files = request.FILES.getlist('file')
            for img in all_files:
                File.objects.create(recipe=new_recipe, file=img)
            # if not all_files:
            #     File.objects.create(recipe=new_recipe, file='horizont.jpg')
           
            return redirect('/')
    else:
        form = RecipeAddForm()
    return render(request,'main/upload.html', {'form':form })


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    '''update'''
    model = Recipe
    fields = ['title','description','category']
    # fields = '__all__'
    template_name = 'main/upload.html'
    context_object_name = 'Recipe'
    # form_class = RecipeAddForm
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super(RecipeUpdateView, self).get_context_data(**kwargs)
        current_object = self.object
        images = File.objects.filter(recipe=current_object)
        context['image_form'] = ImagesFormSet(instance=current_object)
        return context
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        author = User.objects.filter(id=self.request.user.id).first()

food_recipes/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	{% block title %}<title> </title>{% endblock %}

	{% block bootsrap %}
	{% load bootstrap5 %}

	{# CSS Bootstrap #}
	{% bootstrap_css %} 
	{% endblock bootsrap %}
	<link rel="shortcut icon" type="image/ico" href="{% static 'images/favicon.ico' %}" />

	<!-- Google font -->
	<!-- <link href="https://fonts.googleapis.com/css?family=Hind:400,700" rel="stylesheet"> -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/fnt.css' %}" />

	<!-- Bootstrap -->
	<!-- <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" /> -->

	<!-- Slick -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}" />

	<!-- nouislider -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}" />

	<!-- Font Awesome Icon -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />

	<link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css" rel="stylesheet" />
	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />

	<link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}" />
	

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>
	<!-- HEADER -->
	{% include 'main/header.html' %}
	<!-- /HEADER -->

	<!-- NAVIGATION -->
	{% block sidebar %}
	{% include 'main/sidebar.html' %}
	{% endblock %}
	<!-- /NAVIGATION -->

	<div class="flex-row bg-color-light">
		{% include 'main/messages.html' %}
	</div>

	<!-- section -->
	{% block body %}
	
	{% endblock %}
	<!-- /section -->

	<!-- FOOTER -->
	{% block footer %}
	
	{% endblock %}
	<!-- /FOOTER -->

	<!-- jQuery Plugins -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/slick.min.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	<script src=" https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js "></script>

	<script src="{% static 'js/site_js.js' %}"></script>

</body>

</html>

food_recipes/main/templates/main/foodlist.html
{% extends 'main/base.html' %}


{% block body %}
{% block title %}<title>{{title}} {{food_type}}</title>{% endblock %}

<body>
    <div class="flex-row bg-color-light">
        <h2 class="text-header  text-end">{{title}} {{food_type}}</h2> 
    </div>


    {% include 'main/short_recipe.html' %}

</body>
{% endblock %}

food_recipes/main/templates/main/gallery.html
{% extends 'main/base.html' %}


{% block body %}
{% block title %}<title>{{title}}</title>{% endblock %}

<body>
    <div class="flex-row bg-color-light">
        <h2 class="text-header  text-end">{{title}}</h2> 
    </div>


    {% include 'main/image_rows.html' %}

</body>
{% endblock %}

food_recipes/main/templates/main/image_rows.html
{% load static %}
{% load tag_library %}

<div class="row d-flex align-content-center justify-content-center flex-wrap">

    {% for recipe in recipes %}
    <div class="col-md-3 product product-single">
        {% with prod_name=files|get_img:recipe.id %}
        <div class="product-thumb" style="height: 200px;   
                        background-image: url('{{ MEDIA_URL }}/{{prod_name}}'); 
                        background-repeat:no-repeat; background-position: center;">

            <a href="{% url 'main:details' id=recipe.id %}">
                <button class="main-btn quick-view"><i class=""></i> смотреть {{recipe.id}}</button>
            </a>
            
        </div>
        {% endwith %}

        {% with liked_it=liked|get_item:recipe.id %}
        <div class="product-body position-relative ">

            <div class="product-rating">
                <p>
                {% if recipe.votes != 0 %}
                    {% if liked_it %}
                    liked_it
                    {% endif %} 
                <i class="fa fa-star"> {{recipe.votes}}</i>

                {% else %} 
                <i class="fa fa-star-o empty"></i>
                {% endif %}   
                </p>
            </div>
            <div class="text-wrap text-break">
                <h3 class="product-price">{{recipe.title}}</h3>
            </div>

            <div class="product-btns">
                <div class="w-100">
                {% if user.is_authenticated %}
                <button class="main-btn icon-btn {% if liked_it %} liked-btn {% endif %}" {% if liked_it %}  {% else %} onClick="starRecipe({{recipe.id}});"{% endif %} ><i class="fa fa-heart"></i></button>
                <!-- <button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button> -->
                {% endif %}
                автор: {{recipe.author.account.nickname}}</div>
            </div>
        </div>
        {% endwith %}   
    </div>
    {% endfor %}

    {% include 'main/paginations.html' %}
</div>

food_recipes/main/templates/main/index.html
{% extends 'main/base.html' %}


{% block body %}
{% block title %}<title>{{title}}</title>{% endblock %}

<body>
    <div clss="container p-0">
        <div class="flex-row bg-color-light">
            <!-- <div class="col-9"></div> -->
            <div class="">
                <form method="post">
                    {% csrf_token %}
                    
                        <div>
                            <div class="col-2 col-flex d-flex justify-content-end"><a href="{% url 'main:top' %}">Посмотреть топ юзеров</a></div>
                            <div class="d-flex justify-content-end">
                                <input type="text" name="title" placeholder="ищу рецепт">
                                <button type="submit" class="btn primary-btn">Поиск</button>
                            </div>
                        </div>
                    
                </form>
            </div>
        </div>

      
    </div>

    <div clss="container p-0">
    <div class="flex-row bg-color-light">
        {% if search_res %}
        <h4>Результаты поиска по запросу: {{search_res}}</h4>
        {% endif %}
    </div>
    </div>
    

    {% include 'main/image_rows.html' %}

</body>
{% endblock %}

food_recipes/main/templates/main/recipe.html
{% extends 'main/base.html' %}
{% load static %}
{% load tag_library %}

{% block body %}
{% block title %}<title>{{title}}</title>{% endblock %}

<body>
    <div class="flex-row bg-color-light">
        <h2 class="text-header text-end">Детали рецепта</h2>
    </div>

    <div class="container">
        <div>

            <h3>{{recipe.title}}</h3>
            
            {% if recipe.author.id == request.user.id %} 
            <div>
                <a href="{% url 'main:rec_update' pk=recipe.id %}"><i class="fa fa-regular fa-pencil-square-o"></i> Редактировать </a>
            </div>
            <div>
                <a href="#" onClick="ConfirmDialog(this);" data-rec_id="{{recipe.id}}"><i class="fa fa-regular fa-trash"></i> Удалить рецепт </a>
            </div>
            {% endif %}
            
                <p>
                {% if recipe.votes != 0 %}
                <i class="fa fa-star"> {{recipe.votes}}</i>
                {% else %} 
                <i class="fa fa-star-o empty"></i>
                {% endif %}                      
                </p>


            <p><div class="col-auto d-inline-flex"><a href="{% url 'users:user' pk=recipe.author.id %}">{{recipe.author.account.nickname}}</a></div>
            
            </p>
            <p>{{recipe.date}}</p>
            <div class="pb-3">{{recipe.description|linebreaks}}</div>
        </div>
        <div class="row">

            {% for file in files %}
            <div class="col-md-6 col-sm-12 flexbox">
                <div class="product product-single w-100">
                    <div class="product-thumb h-100">
                        {% with prod_name='import/'|add:file.file %}
                        <img src="{{file.file.url}}" height="100%" alt="image">
                        {% endwith %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</body>
{% endblock %}

food_recipes/main/templates/main/short_recipe.html
{% load static %}
{% load tag_library %}


<div class="row d-flex align-content-center justify-content-center flex-wrap">

    {% for recipe in recipes %}
    <div class="col-12 product product-single">
        
        <div class="row w-100">
            <a  class="col-md-6 col-sm-12 flexbox" href="{% url 'main:details' id=recipe.id %}">
             

               
                <div class="w-75">
                    {% with img=files|get_img:recipe.id %}
                    <img src="{{ MEDIA_URL }}/{{img}}" height="200px" alt="image">
                    {% endwith %}
                </div>
             
            </a>

            <div class="col-md-6 col-sm-12 flexbox bg-color-light">
                <div class="w-100 product-body position-relative ">

                    <div class="product-rating">
                        <p>
                            {% if recipe.votes != 0 %}
                                {% if liked_it %}
                                liked_it
                                {% endif %} 
                            <i class="fa fa-star"> {{recipe.votes}}</i>
            
                            {% else %} 
                            <i class="fa fa-star-o empty"></i>
                            {% endif %}   
                            </p>
                    </div>
                    <div class="text-wrap text-break w-100">
                        <a href="{% url 'main:details' id=recipe.id %}"><h3 class="product-price">{{recipe.title}}</h3></a>
                        <div class="w-100">{{recipe.description}}</div>
                    </div>

                 
                </div>

            </div>
        </div>
        

    </div>
    {% endfor %}

    {% include 'main/paginations.html' %}

</div>

food_recipes/main/templates/main/sidebar.html
{% load static %}
{% load tag_library %}
{% load users_tags %}

<div id="navigation">
    <!-- container -->
    <div class="container">
        <div id="responsive-nav">
            
            <!-- menu nav -->
            <div class="menu-nav">
                

                <span class="menu-header">Меню <i class="fa fa-bars"></i></span>
                <ul class="menu-list">
                    <li>
                        <a href="{% url 'main:main' %}"><h3 class="mr-2 d-none d-md-inline">FOOD GOOD</h3></a>
                    </li>
                     
                    <li>
                        <a href="{% url 'main:main' %}">Главная</a>
                    </li>
                    <li>
                        <a href="{% url 'main:gallery' %}">Галерея</a>
                    </li>                

                    <li class="dropdown dropdown default-dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">Категории

                        </a>
                        <div class="custom-menu">
                            <div class="row">


                                <ul class="list-links">
                                    {% with 'Салаты Торты Выпечка' as items %}
                                    {% for text in items.split %}
                                        <li><a href="{% url 'main:foodlist' cat_id=forloop.counter  %}">{{text}}</a></li>
                                    {% endfor %}
                                    {% endwith %}
                                </ul>
                                <hr class="hidden-md hidden-lg">


                            </div>
                        </div>
                    </li>

                    {# if request.user and request.user|has_group:"Editors" #}
                    <!-- <li>
                        <a href="/admin/"><i class="fa fa-pen-nib menu-icon"></i>Админка</a>
                    </li>  -->
                    {# endif #}
                    
                    {% if request.user and request.user.is_staff %}
                    <li>
                        <a href="/admin/"><i class="fa fa-pen-nib menu-icon"></i>Админка</a>
                    </li> 
                    {% endif %}         

                    <!-- <li>
                        <a href="{% url 'main:contacts' %}">Контакты</a>
                    </li>  -->

                    <li class="header-account dropdown default-dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                            аккаунт 
                        </a>
                        <div class="custom-menu">
                            <div class="row">
                                <div class="list-links">
                                    <ul class="">
                                        
                                       
                                        {% if user.is_authenticated %}
                                        <li><a href="#" onClick="myRecipes();"><i class="fa fa-regular fa-arrow-circle-right"></i> Мои рецепты</a></li>
                                        <li><a href="{% url 'main:add_rec' %}"><i class="fa fa-regular fa-arrow-circle-right"></i> Добавить рецепт</a></li>
                                        <li><a href="{% url 'users:account' pk=user.id %}"><i class="fa fa-regular fa-address-book"></i> Мой профиль</a></li>
                                        <li><a href="{% url 'users:logout' %}"><i class="fa fa-regular fa-arrow-circle-right"></i> Выход</a></li>
                                        {% else %}
                                        <li><a href="{% url 'users:login' %}"><i class="fa fa-regular fa-arrow-circle-right"></i> Вход в аккаунт</a></li>
                                        <li><a href="{% url 'users:register' %}"><i class="fa fa-regular fa-user-circle-o"></i> Регистрация</a></li>
                                        {% endif %}

                                        
                                       
                                    </ul>

                                </div>

                            </div>
                        </div>
                    </li> 
                </ul>
            </div>
            <!-- menu nav -->


        </div>
    </div>
</div>

food_recipes/main/templates/main/users_top.html
{% extends 'main/base.html' %}


{% block body %}
{% block title %}<title>{{title}}</title>{% endblock %}

<body>
    <div class="container pt-2">
        <h3 class="product-price">Топ пользователей</h3>
    <div class="flex-row align-content-center justify-content-center mt-4">

        <div class="col-lg-6 align-content-center justify-content-center text-left">
            {% for user in users_top %}
            <div clss="row d-inline-flex align-content-center justify-content-center ">
                <ul>
                    <li>
                        
                        <div class="col-auto d-inline-flex"><a href="{% url 'users:user' pk=user.id %}">{{user.account.nickname}}</a></div>
                        <!-- <div class="col-1 d-inline-flex">({{user.username}})</div> -->
                        <div class="col-4 d-inline-flex">- {{user.recipe__count}} рецепт(ов) опубликовано</div>
                       
                    </li>
                </ul>


            </div>
            {% endfor %}
        </div>
    </div>
    </div>


</body>
{% endblock %}